image: node:lts
cache:    
  - key:        
      files:          
        - package-lock.json   
    paths:      
      - node_modules/

stages:
  - install
  - validate
  - deploy

variables:
  FF_USE_FASTZIP: "true"
  ARTIFACT_COMPRESSION_LEVEL: fastest
  CACHE_COMPRESSION_LEVEL: fastest
  TRANSFER_METER_FREQUENCY: 5s

install:
  stage: install
  script:
    - npm install
  artifacts:      
    paths:       
     - node_modules/
     
test:
  stage: validate
  script:
    - npm run test

lint:
  stage: validate
  script:
    - npm run lint

prettier:
  stage: validate
  script:
    - npm run prettier

deploy:
  stage: deploy
  script:
    - npm run build
    - npx netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
